project:
  type: book

book:
  title: "gm2_book"
  author: "MG"
  date: "11/22/2023"
  chapters:
    - index.qmd
    - Mpi.qmd
    - MK.qmd
    - pi0.qmd
    - scale_setting.qmd
    - continuum_amu_s_full.qmd
    - continuum_amu_s_W.qmd
    - continuum_amu_s_sd.qmd
    - continuum_amu_l_W.qmd
    - continuum_amu_l_sd.qmd
    - blinded_B64.qmd
    - blinded_C80.qmd
    - blinded_D96.qmd
    - blinded_continuum.qmd
    - difference_continuum.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: default
    html-math-method: katex


