# blinded continuum

```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
# library(hadron)
#library(kableExtra) # breaks latex
#library(tidyverse)

df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knit handle the plot
myplotly(ggplot())
#widgetframe::frameableWidget(ggplotly(ggp)%>%config(mathjax = "cdn") )
```

the different bounding are:

- Above
  
  1) $c(t>t_c)< c(t_c) e^{-E_{2\pi} (t-t_c)}$
  
  2) $c(t>t_c)< c(t_c) e^{-M_{eff} (t-t_c)}$
    where $M_{eff}$ is the plateau value of $m_{eff}(t)$ of the correlator VKVK.

- below 

  1) $c(t>t_c) > 0$
  
  2) $c(t>t_c)< c(t_c) e^{-m_{eff}(t_m) (t-t_c)}$, where $t_m=t_c$ for  $t_c<t_e$
    while $t_m=t_e$ for $t_c\geq t_e$ and $t_e$ is some time slice

# $c(t)>0$ bound: above 1) and below 1) (BMW)

```{r, results='asis', echo=FALSE, warning=FALSE}
source("/home/garofalo/programs/Rose/R/plot_routines.R")
dir<-"/home/garofalo/analysis/blinded_gm2/data/fit_all/"
namefit<-paste0(dir,"amu_bound_a2_GS_L_Mpi")
file<-paste0(namefit,"_fit_P.dat")
fit<- read_fit_P_file(file)
cat("\n\n")
dt<-make_table_fit_result(fit)
print(dt)
gg<-myggplot()
gg<-plot_fit(basename = namefit, var="afm",data_type = c("TM","OS"), width=1e-4, gg=gg
                 ,               id_color = 5, id_shape = 5,
             # , labelfit = "zap"
                ,single_name_for_fit ="fit"
             #, nolabel_for_fit = TRUE
               )
fig<-myplotly(gg, "","$a^2[fm]$",
            paste0("$a_\\mu$"), to_print = TRUE)
```

# $m_eff(t)$ bound: above 1) and below 2) (Tov or RBC/UKQCD)

```{r, results='asis', echo=FALSE, warning=FALSE}
dir<-"/home/garofalo/analysis/blinded_gm2/data/fit_all/"
namefit<-paste0(dir,"amu_bound_meff_t_a2_GS_L_Mpi")
file<-paste0(namefit,"_fit_P.dat")
fit<- read_fit_P_file(file)
cat("\n\n")
dt<-make_table_fit_result(fit)
print(dt)
gg<-myggplot()
gg<-plot_fit(basename = namefit, var="afm",data_type = c("TM","OS"), width=1e-4, gg=gg
                 ,               id_color = 5, id_shape = 5,
             # , labelfit = "zap"
                ,single_name_for_fit ="fit"
             #, nolabel_for_fit = TRUE
               )
fig<-myplotly(gg, "","$a^2[fm]$",
            paste0("$a_\\mu$"), to_print = TRUE)
```

# $M_{eff}$ bound: above 2) and below 2)

```{r, results='asis', echo=FALSE, warning=FALSE}
dir<-"/home/garofalo/analysis/blinded_gm2/data/fit_all/"
namefit<-paste0(dir,"amu_bound_meff_a2_GS_L_Mpi")
file<-paste0(namefit,"_fit_P.dat")
fit<- read_fit_P_file(file)
cat("\n\n")
dt<-make_table_fit_result(fit)
print(dt)
gg<-myggplot()
gg<-plot_fit(basename = namefit, var="afm",data_type = c("TM","OS"), width=1e-4, gg=gg
                 ,               id_color = 5, id_shape = 5,
             # , labelfit = "zap"
                ,single_name_for_fit ="fit"
             #, nolabel_for_fit = TRUE
               )
fig<-myplotly(gg, "","$a^2[fm]$",
            paste0("$a_\\mu$"), to_print = TRUE)
```

## All data from different bounds


```{r, results='asis', echo=FALSE, warning=FALSE}
dir<-"/home/garofalo/analysis/blinded_gm2/data/fit_all/"
gg<-myggplot()
namefit<-paste0(dir,"amu_bound_a2_GS_L_Mpi")
file<-paste0(namefit,"_fit_P.dat")
gg<-plot_fit(basename = namefit, var="afm",data_type = c("TM","OS"), width=1e-4, gg=gg
                 ,               id_color = 5, id_shape = 5,
             # , labelfit = "zap"
                ,single_name_for_fit ="fit"
             #, nolabel_for_fit = TRUE
             ,noribbon = TRUE
               )
namefit<-paste0(dir,"amu_bound_meff_t_a2_GS_L_Mpi")
file<-paste0(namefit,"_fit_P.dat")
gg<-plot_fit(basename = namefit, var="afm",data_type = c("TM-meff_t","OS-meff_t"), width=1e-4, gg=gg
                 ,               id_color = 5, id_shape = 5,
             # , labelfit = "zap"
                ,single_name_for_fit ="fit-meff_t"
             #, nolabel_for_fit = TRUE
             ,nudge = 0.00004,noribbon = TRUE
               )
namefit<-paste0(dir,"amu_bound_meff_a2_GS_L_Mpi")
file<-paste0(namefit,"_fit_P.dat")
gg<-plot_fit(basename = namefit, var="afm",data_type = c("TM-meff","OS-meff"), width=1e-4, gg=gg
                 ,               id_color = 5, id_shape = 5,
             # , labelfit = "zap"
                ,single_name_for_fit ="fit-meff"
             #, nolabel_for_fit = TRUE
             ,nudge = 0.00008,
             noribbon = TRUE
               )


fig<-myplotly(gg, "","$a^2[fm]$",
            paste0("$a_\\mu$"), to_print = TRUE, xrange=c(0,0.0065))
```