## $M_\pi$ {#Mpi}

```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
# library(hadron)
#library(kableExtra) # breaks latex
#library(tidyverse)

df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knit handle the plot
myplotly(ggplot())
#widgetframe::frameableWidget(ggplotly(ggp)%>%config(mathjax = "cdn") )
```


```{r, results='asis',echo=FALSE}
ens<-c(
      # "cA.30.32_mu.0.003000",
      #  "cA.40.24_mu.0.004000",
      #  "cA.53.24_mu.0.005300",
       "cB.72.64_mu.0.000720",
       "cB.72.96_mu.0.000720",
       "cC.06.80_mu.0.000600",
       "cD.54.96_mu.0.000540",
       "cE.44.112_mu.0.000440"
       )
source("/home/garofalo/programs/Rose/R/read_block.R")
dir <-"/home/garofalo/analysis/g-2_new_stat/out/"
df<-NULL
for (e in ens){
  mt<-read_df(paste0(dir,e,"_output"))
  all_obs<-Rose::get_all_corr(mt)
  df<-add_corr_to_df("M_{PS}^{op}",all_obs ,mt,df, 
                     rename = paste0("Mpi-",substr( e , start = 1 , stop = 8 )))
  
  fit<-get_full_res("M_{PS}^{op}",all_obs ,mt)
  cat(fit[1,1],fit[1,2],"<br />")
}
gg<-plot_df_corr_ggplot(df)
fig<-myplotly(gg, to_print = TRUE)
```
