# $M_\pi$ reweighting


```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
# library(hadron)
# library(kableExtra) # breaks latex
# library(tidyverse)

df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x, y)) +
    geom_point()
  assign("ggp", plotly::ggplotly(gg), envir = parent.frame())
  # ggp
  df # NOT returning a plot
}
res1 <- f1(df)
ggp # Let knit handle the plot
myplotly(ggplot())
# widgetframe::frameableWidget(ggplotly(ggp)%>%config(mathjax = "cdn") )
```




```{r, echo=FALSE, results='asis', dev='tikz', warning=FALSE}


dir <- "/home/garofalo/analysis/g-2_new_stat/fit_all_rew/"
name<-"aMpi2_over_afpi2_A12_noC20_cor_cov_unitary"
namefit <- paste0(dir, name)
file <- paste0(namefit, "_fit_P.dat")
fit <- read_fit_P_file(file)
dt <- make_table_fit_result(fit)
print(dt)


gg <- plot_fit(
  basename = namefit,
  var = "amu",
  id_x = 1,
  data_type = c("A", "B", "C", "D", "E", "B", "C", "D"),
  width = 1e-4,
  gg = NULL, 
  labelfit = "",
  # , single_name_for_fit = "fit"
  # , nolabel_for_fit = TRUE
  noline = TRUE
)

# filed <- paste0(namefit, "_fit_data.txt")
# df <- read.table(filed, header = FALSE, fill = TRUE)
# idy <- ncol(df) - 2
# kable(df[, c(1,2,3,4,idy,idy+1)],col.names =c("mu","aMpi","afpi","L","afpi-inf","err") )
gg <- gg + geom_hline(yintercept = 1.07015457788)
fig <- myplotly(gg, "", "$a\\mu_\\ell$", "$(M_\\pi/f_\\pi)^2$", to_print = TRUE)
df<-read.table(paste0(dir,name,"_amul_res.txt"))

# df<-read.table(paste0(dir,"aMpi2_over_afpi2_a2_A_cov_amul_res.txt"))
# df1<-read.table(paste0(dir,"aMpi2_over_afpi2_a2_A_no_max_twist_cov_amul_res.txt"))
dft<-df[,c(1,2)]
dft[,2] <- mapply(mean_print, df[,2],df[,3])
loop<- df

# dft[,3] <- mapply(mean_print, df1[,2],df1[,3])
kable(dft, col.names = c("Ens.","$a\\mu_\\ell$"))

```




```{r, echo=FALSE, results='asis', dev='tikz', warning=FALSE}

dir <- "/home/garofalo/analysis/g-2_new_stat/fit_all_rew/"
name<-"aMpi2_over_afpi2_A12_noC20_rew"
namefit <- paste0(dir, name)
file <- paste0(namefit, "_fit_P.dat")
fit <- read_fit_P_file(file)
dt <- make_table_fit_result(fit)
print(dt)


gg <- plot_fit(
  basename = namefit,
  var = "amu",
  id_x = 1,
  data_type = c("A", "B", "C", "D", "E", "B", "C", "D"),
  width = 1e-4,
  gg = NULL, 
  labelfit = "",
  # , single_name_for_fit = "fit"
  # , nolabel_for_fit = TRUE
  noline = TRUE
)

# filed <- paste0(namefit, "_fit_data.txt")
# df <- read.table(filed, header = FALSE, fill = TRUE)
# idy <- ncol(df) - 2
# kable(df[, c(1,2,3,4,idy,idy+1)],col.names =c("mu","aMpi","afpi","L","afpi-inf","err") )
gg <- gg + geom_hline(yintercept = 1.07015457788)
fig <- myplotly(gg, "", "$a\\mu_\\ell$", "$(M_\\pi/f_\\pi)^2$", to_print = TRUE)
df<-read.table(paste0(dir,name,"_amul_res.txt"))

# df<-read.table(paste0(dir,"aMpi2_over_afpi2_a2_A_cov_amul_res.txt"))
# df1<-read.table(paste0(dir,"aMpi2_over_afpi2_a2_A_no_max_twist_cov_amul_res.txt"))
dft<-df[,c(1,2)]
dft[,2] <- mapply(mean_print, df[,2],df[,3])
rew<-df
# dft[,3] <- mapply(mean_print, df1[,2],df1[,3])
kable(dft, col.names = c("Ens.","$a\\mu_\\ell$"))

```


```{r, echo=FALSE, results='asis', dev='tikz', warning=FALSE}
gg <- myggplot()
dir <- "/home/garofalo/analysis/g-2_new_stat/fit_all_rew/"
namefit <- paste0(dir, "afpi_max_twist_A12_noC20_rew")
file <- paste0(namefit, "_fit_P.dat")
fit_a <- read_fit_P_file(file)

gg <- gg + geom_pointrange(aes(
  x = fit_a$P[c(1:5), 2]^2, y = loop[,2]-loop[,2],
  ymin = loop[,2] - loop[,3]-loop[,2],
  ymax = loop[,2] + loop[,3]-loop[,2],
  color = "iter0",
  shape = "iter0",
  fill = "iter0"
))

gg <- gg + geom_pointrange(aes(
  x = fit_a$P[c(1:5), 2]^2+1e-4, y = rew[,2]-loop[,2],
  ymin = rew[,2] - rew[,3]-loop[,2],
  ymax = rew[,2] + rew[,3]-loop[,2],
  color = "loop",
  shape = "loop",
  fill = "loop"
))
fig <- myplotly(gg, "", "$a^2(rew)$", "$m_\\ell(X)-m_\\ell(\\mbox{sc-paper})$", to_print = TRUE, xrange = c(0, 0.0085))
```